// Dashboard
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_IS_SIDEBAR_OPEN = "SET_IS_SIDEBAR_OPEN";

//! Common
export const OPEN_TEXT_MODAL = 'OPEN_TEXT_MODAL';
export const CLOSE_TEXT_MODAL = 'CLOSE_TEXT_MODAL';

//! Astrologer
export const GET_ASTROLOGER = 'GET_ASTROLOGER';
export const SET_ASTROLOGER = 'SET_ASTROLOGER';
export const GET_ENQUIRY_ASTROLOGER = 'GET_ENQUIRY_ASTROLOGER';
export const SET_ENQUIRY_ASTROLOGER = 'SET_ENQUIRY_ASTROLOGER';
export const GET_ASTROLOGER_BY_ID = 'GET_ASTROLOGER_BY_ID';
export const SET_ASTROLOGER_BY_ID = 'SET_ASTROLOGER_BY_ID';
export const CREATE_ASTROLOGER = 'CREATE_ASTROLOGER';
export const UPDATE_ASTROLOGER_BY_ID = 'UPDATE_ASTROLOGER_by_ID';
export const DELETE_ASTROLOGER_BY_ID = 'DELETE_ASTROLOGER_by_ID';
export const GET_CHAT_HISTORY_BY_ASTROLOGER_ID = 'GET_CHAT_HISTORY_BY_ASTROLOGER_ID';
export const SET_CHAT_HISTORY_BY_ASTROLOGER_ID = 'SET_CHAT_HISTORY_BY_ASTROLOGER_ID';
export const GET_CALL_HISTORY_BY_ASTROLOGER_ID = 'GET_CALL_HISTORY_BY_ASTROLOGER_ID';
export const SET_CALL_HISTORY_BY_ASTROLOGER_ID = 'SET_CALL_HISTORY_BY_ASTROLOGER_ID';
export const GET_VIDEO_CALL_HISTORY_BY_ASTROLOGER_ID = 'GET_VIDEO_CALL_HISTORY_BY_ASTROLOGER_ID';
export const SET_VIDEO_CALL_HISTORY_BY_ASTROLOGER_ID = 'SET_VIDEO_CALL_HISTORY_BY_ASTROLOGER_ID';
export const GET_LIVE_HISTORY_BY_ASTROLOGER_ID = 'GET_LIVE_HISTORY_BY_ASTROLOGER_ID';
export const SET_LIVE_HISTORY_BY_ASTROLOGER_ID = 'SET_LIVE_HISTORY_BY_ASTROLOGER_ID';
export const GET_GIFT_HISTORY_BY_ASTROLOGER_ID = 'GET_GIFT_HISTORY_BY_ASTROLOGER_ID';
export const SET_GIFT_HISTORY_BY_ASTROLOGER_ID = 'SET_GIFT_HISTORY_BY_ASTROLOGER_ID';
export const GET_REVIEW_BY_ASTROLOGER_ID = 'GET_REVIEW_BY_ASTROLOGER_ID';
export const SET_REVIEW_BY_ASTROLOGER_ID = 'SET_REVIEW_BY_ASTROLOGER_ID';
export const GET_TRANSACTION_HISTORY_BY_ASTROLOGER_ID = 'GET_TRANSACTION_HISTORY_BY_ASTROLOGER_ID';
export const SET_TRANSACTION_HISTORY_BY_ASTROLOGER_ID = 'SET_TRANSACTION_HISTORY_BY_ASTROLOGER_ID';
export const GET_PUJA_HISTORY_BY_ASTROLOGER_ID = 'GET_PUJA_HISTORY_BY_ASTROLOGER_ID';
export const SET_PUJA_HISTORY_BY_ASTROLOGER_ID = 'SET_PUJA_HISTORY_BY_ASTROLOGER_ID';
export const UPDATE_WALLET_BY_ASTROLOGER_ID = 'UPDATE_WALLET_BY_ASTROLOGER_ID';
export const VERIFY_ASTROLOGER_PROFILE = 'VERIFY_ASTROLOGER_PROFILE';
export const CHANGE_ASTROLOGER_CHAT_STATUS = 'CHANGE_ASTROLOGER_CHAT_STATUS';
export const CHANGE_ASTROLOGER_CALL_STATUS = 'CHANGE_ASTROLOGER_CALL_STATUS';
export const CHANGE_ASTROLOGER_VIDEO_CALL_STATUS = 'CHANGE_ASTROLOGER_VIDEO_CALL_STATUS';
export const GET_ASTROLOGER_WITHDRAWAL_REQUEST = 'GET_ASTROLOGER_WITHDRAWAL_REQUEST';
export const SET_ASTROLOGER_WITHDRAWAL_REQUEST = 'SET_ASTROLOGER_WITHDRAWAL_REQUEST';
export const APPROVE_ASTROLOGER_WITHDRAWAL_REQUEST_AMOUNT = 'APPROVE_ASTROLOGER_WITHDRAWAL_REQUEST_AMOUNT';

export const GET_ASTROLOGER_INQUIRY = 'GET_ASTROLOGER_INQUIRY';
export const SET_ASTROLOGER_INQUIRY = 'SET_ASTROLOGER_INQUIRY';

//! Live
export const GET_LIVE = 'GET_LIVE';
export const SET_LIVE = 'SET_LIVE';
export const DELETE_LIVE = 'DELETE_LIVE';


//! Customer
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const SET_CUSTOMER = 'SET_CUSTOMER';
export const GET_CUSTOMER_BY_ID = 'GET_CUSTOMER_BY_ID';
export const SET_CUSTOMER_BY_ID = 'SET_CUSTOMER_BY_ID';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const UPDATE_CUSTOMER_BY_ID = 'UPDATE_CUSTOMER_by_ID';
export const DELETE_CUSTOMER_BY_ID = 'DELETE_CUSTOMER_by_ID';
export const CHANGE_CUSTOMER_BANNED_UNBANNED_STATUS = 'CHANGE_CUSTOMER_BANNED_UNBANNED_STATUS';
export const UPDATE_WALLET_BY_CUSTOMER_ID = 'UPDATE_WALLET_BY_CUSTOMER_ID';
export const GET_CHAT_HISTORY_BY_CUSTOMER_ID = 'GET_CHAT_HISTORY_BY_CUSTOMER_ID';
export const SET_CHAT_HISTORY_BY_CUSTOMER_ID = 'SET_CHAT_HISTORY_BY_CUSTOMER_ID';
export const GET_CALL_HISTORY_BY_CUSTOMER_ID = 'GET_CALL_HISTORY_BY_CUSTOMER_ID';
export const SET_CALL_HISTORY_BY_CUSTOMER_ID = 'SET_CALL_HISTORY_BY_CUSTOMER_ID';
export const GET_VIDEO_CALL_HISTORY_BY_CUSTOMER_ID = 'GET_VIDEO_CALL_HISTORY_BY_CUSTOMER_ID';
export const SET_VIDEO_CALL_HISTORY_BY_CUSTOMER_ID = 'SET_VIDEO_CALL_HISTORY_BY_CUSTOMER_ID';
export const GET_LIVE_HISTORY_BY_CUSTOMER_ID = 'GET_LIVE_HISTORY_BY_CUSTOMER_ID';
export const SET_LIVE_HISTORY_BY_CUSTOMER_ID = 'SET_LIVE_HISTORY_BY_CUSTOMER_ID';
export const GET_PUJA_HISTORY_BY_CUSTOMER_ID = 'GET_PUJA_HISTORY_BY_CUSTOMER_ID';
export const SET_PUJA_HISTORY_BY_CUSTOMER_ID = 'SET_PUJA_HISTORY_BY_CUSTOMER_ID';
export const GET_ORDER_HISTORY_BY_CUSTOMER_ID = 'GET_ORDER_HISTORY_BY_CUSTOMER_ID';
export const SET_ORDER_HISTORY_BY_CUSTOMER_ID = 'SET_ORDER_HISTORY_BY_CUSTOMER_ID';
export const GET_FOLLOWING_HISTORY_BY_CUSTOMER_ID = 'GET_FOLLOWING_HISTORY_BY_CUSTOMER_ID';
export const SET_FOLLOWING_HISTORY_BY_CUSTOMER_ID = 'SET_FOLLOWING_HISTORY_BY_CUSTOMER_ID';
export const GET_REVIEW_HISTORY_BY_CUSTOMER_ID = 'GET_REVIEW_HISTORY_BY_CUSTOMER_ID';
export const SET_REVIEW_HISTORY_BY_CUSTOMER_ID = 'SET_REVIEW_HISTORY_BY_CUSTOMER_ID';
export const GET_MUDRA_HISTORY_BY_CUSTOMER_ID = 'GET_MUDRA_HISTORY_BY_CUSTOMER_ID';
export const SET_MUDRA_HISTORY_BY_CUSTOMER_ID = 'SET_MUDRA_HISTORY_BY_CUSTOMER_ID';
export const GET_MUDRA_REQUEST_HISTORY_BY_CUSTOMER_ID = 'GET_MUDRA_REQUEST_HISTORY_BY_CUSTOMER_ID';
export const SET_MUDRA_REQUEST_HISTORY_BY_CUSTOMER_ID = 'SET_MUDRA_REQUEST_HISTORY_BY_CUSTOMER_ID';

//! Astro-Puja
export const GET_PUJA = 'GET_PUJA';
export const SET_PUJA = 'SET_PUJA';
export const CREATE_PUJA = 'CREATE_PUJA';
export const UPDATE_PUJA = 'UPDATE_PUJA';
export const DELETE_PUJA = 'DELETE_PUJA';
export const GET_PUJA_REQUEST = 'GET_PUJA_REQUEST';
export const SET_PUJA_REQUEST = 'SET_PUJA_REQUEST';
export const ASSIGN_PUJA = 'ASSIGN_PUJA';
export const CHANGE_PUJA_STATUS = 'CHANGE_PUJA_STATUS';
export const GET_PUJA_BOOKED = 'GET_PUJA_BOOKED';
export const SET_PUJA_BOOKED = 'SET_PUJA_BOOKED';
export const GET_PUJA_HISTORY = 'GET_PUJA_HISTORY';
export const SET_PUJA_HISTORY = 'SET_PUJA_HISTORY';

//! History
export const GET_CHAT_HISTORY = "GET_CHAT_HISTORY";
export const SET_CHAT_HISTORY = "SET_CHAT_HISTORY";
export const GET_CALL_HISTORY = "GET_CALL_HISTORY";
export const SET_CALL_HISTORY = "SET_CALL_HISTORY";
export const GET_VIDEO_CALL_HISTORY = "GET_VIDEO_CALL_HISTORY";
export const SET_VIDEO_CALL_HISTORY = "SET_VIDEO_CALL_HISTORY";
export const GET_LIVE_HISTORY = "GET_LIVE_HISTORY";
export const SET_LIVE_HISTORY = "SET_LIVE_HISTORY";
export const GET_GIFT_HISTORY = "GET_GIFT_HISTORY";
export const SET_GIFT_HISTORY = "SET_GIFT_HISTORY";
export const GET_MUDRA_HISTORY = 'GET_MUDRA_HISTORY';
export const SET_MUDRA_HISTORY = 'SET_MUDRA_HISTORY';
export const GET_MUDRA_REQUEST_HISTORY = 'GET_MUDRA_REQUEST_HISTORY';
export const SET_MUDRA_REQUEST_HISTORY = 'SET_MUDRA_REQUEST_HISTORY';

//! Skill
export const GET_SKILL = 'GET_SKILL';
export const SET_SKILL = 'SET_SKILL';
export const CREATE_SKILL = 'CREATE_SKILL';
export const UPDATE_SKILL = 'UPDATE_SKILL';
export const DELETE_SKILL = 'DELETE_SKILL';

//! Testimonial
export const GET_TESTIMONIAL = 'GET_TESTIMONIAL';
export const SET_TESTIMONIAL = 'SET_TESTIMONIAL';
export const CREATE_TESTIMONIAL = 'CREATE_TESTIMONIAL';
export const UPDATE_TESTIMONIAL = 'UPDATE_TESTIMONIAL';
export const DELETE_TESTIMONIAL = 'DELETE_TESTIMONIAL';

//! Temple Foundation
export const GET_TEMPLE_FOUNDATION = 'GET_TEMPLE_FOUNDATION';
export const SET_TEMPLE_FOUNDATION = 'SET_TEMPLE_FOUNDATION';
export const CREATE_TEMPLE_FOUNDATION = 'CREATE_TEMPLE_FOUNDATION';
export const UPDATE_TEMPLE_FOUNDATION = 'UPDATE_TEMPLE_FOUNDATION';
export const DELETE_TEMPLE_FOUNDATION = 'DELETE_TEMPLE_FOUNDATION';


//! Religious
export const GET_RELIGIOUS_CATEGORY = 'GET_RELIGIOUS_CATEGORY';
export const SET_RELIGIOUS_CATEGORY = 'SET_RELIGIOUS_CATEGORY';
export const CREATE_RELIGIOUS_CATEGORY = 'CREATE_RELIGIOUS_CATEGORY';
export const UPDATE_RELIGIOUS_CATEGORY = 'UPDATE_RELIGIOUS_CATEGORY';
export const DELETE_RELIGIOUS_CATEGORY = 'DELETE_RELIGIOUS_CATEGORY';

export const GET_RELIGIOUS_SUB_CATEGORY = 'GET_RELIGIOUS_SUB_CATEGORY';
export const SET_RELIGIOUS_SUB_CATEGORY = 'SET_RELIGIOUS_SUB_CATEGORY';
export const CREATE_RELIGIOUS_SUB_CATEGORY = 'CREATE_RELIGIOUS_SUB_CATEGORY';
export const UPDATE_RELIGIOUS_SUB_CATEGORY = 'UPDATE_RELIGIOUS_SUB_CATEGORY';
export const DELETE_RELIGIOUS_SUB_CATEGORY = 'DELETE_RELIGIOUS_SUB_CATEGORY';

//! Remedies
export const GET_REMEDIES = 'GET_REMEDIES';
export const SET_REMEDIES = 'SET_REMEDIES';
export const CREATE_REMEDIES = 'CREATE_REMEDIES';
export const UPDATE_REMEDIES = 'UPDATE_REMEDIES';
export const DELETE_REMEDIES = 'DELETE_REMEDIES';

//! Expertise
export const GET_EXPERTISE = "GET_EXPERTISE";
export const SET_EXPERTISE = "SET_EXPERTISE";
export const CREATE_EXPERTISE = "CREATE_EXPERTISE";
export const UPDATE_EXPERTISE = "UPDATE_EXPERTISE";
export const DELETE_EXPERTISE = "DELETE_EXPERTISE";
export const GET_MAIN_EXPERTISE = "GET_MAIN_EXPERTISE";
export const SET_MAIN_EXPERTISE = "SET_MAIN_EXPERTISE";
export const CREATE_MAIN_EXPERTISE = "CREATE_MAIN_EXPERTISE";
export const UPDATE_MAIN_EXPERTISE = "UPDATE_MAIN_EXPERTISE";
export const DELETE_MAIN_EXPERTISE = "DELETE_MAIN_EXPERTISE";

//! Static Page
export const GET_TERMS_AND_CONDITION = 'GET_TERMS_AND_CONDITION';
export const SET_TERMS_AND_CONDITION = 'SET_TERMS_AND_CONDITION';
export const CREATE_TERMS_AND_CONDITION = 'CREATE_TERMS_AND_CONDITION';
export const GET_PRIVACY_POLICY = 'GET_PRIVACY_POLICY';
export const SET_PRIVACY_POLICY = 'SET_PRIVACY_POLICY';
export const CREATE_PRIVACY_POLICY = 'CREATE_PRIVACY_POLICY';
export const GET_ABOUT_US = 'GET_ABOUT_US';
export const SET_ABOUT_US = 'SET_ABOUT_US';
export const CREATE_ABOUT_US = 'CREATE_ABOUT_US';


//! Temple
export const GET_TEMPLE_DARSHAN = 'GET_TEMPLE_DARSHAN';
export const SET_TEMPLE_DARSHAN = 'SET_TEMPLE_DARSHAN';
export const GET_TEMPLE_DARSHAN_BY_ID = 'GET_TEMPLE_DARSHAN_BY_ID';
export const SET_TEMPLE_DARSHAN_BY_ID = 'SET_TEMPLE_DARSHAN_BY_ID';
export const CREATE_TEMPLE_DARSHAN = 'CREATE_TEMPLE_DARSHAN';
export const UPDATE_TEMPLE_DARSHAN = 'UPDATE_TEMPLE_DARSHAN';
export const DELETE_TEMPLE_DARSHAN = 'DELETE_TEMPLE_DARSHAN';
export const DELETE_TEMPLE_IMAGE = 'DELETE_TEMPLE_IMAGE';
export const DELETE_TEMPLE_VIDEO = 'DELETE_TEMPLE_VIDEO'
export const UPDATE_TEMPLE_DARSHAN_IMAGE = 'UPDATE_TEMPLE_DARSHAN_IMAGE';

export const GET_TEMPLE_MANDIR = 'GET_TEMPLE_MANDIR';
export const SET_TEMPLE_MANDIR = 'SET_TEMPLE_MANDIR';
export const UPDATE_TEMPLE_MANDIR = 'UPDATE_TEMPLE_MANDIR';

//! Temple Video
export const GET_TEMPLE_VIDEO = 'GET_TEMPLE_VIDEO';
export const SET_TEMPLE_VIDEO = 'SET_TEMPLE_VIDEO';
export const CREATE_TEMPLE_VIDEO = 'CREATE_TEMPLE_VIDEO';
export const DELETE_TEMPLE_VIDEO_BY_ID = 'DELETE_TEMPLE_VIDEO_BY_ID';

//? Asset Category
export const GET_TEMPLE_ASSETS = 'GET_TEMPLE_ASSETS';
export const SET_TEMPLE_ASSETS = 'SET_TEMPLE_ASSETS';
export const CREATE_TEMPLE_ASSETS = 'CREATE_TEMPLE_ASSETS';
export const UPDATE_TEMPLE_ASSETS = 'UPDATE_TEMPLE_ASSETS';
export const DELETE_TEMPLE_ASSETS = 'DELETE_TEMPLE_ASSETS';

//? Assets Items
export const GET_TEMPLE_ASSETS_ITEMS_BY_ASSETS_ID = 'GET_TEMPLE_ASSETS_ITEMS_BY_ASSETS_ID';
export const SET_TEMPLE_ASSETS_ITEMS_BY_ASSETS_ID = 'SET_TEMPLE_ASSETS_ITEMS_BY_ASSETS_ID';
export const CREATE_TEMPLE_ASSETS_ITEMS = 'CREATE_TEMPLE_ASSETS_ITEMS';
export const UPDATE_TEMPLE_ASSETS_ITEMS = 'UPDATE_TEMPLE_ASSETS_ITEMS';
export const DELETE_TEMPLE_ASSETS_ITEMS = 'DELETE_TEMPLE_ASSETS_ITEMS';

//? Live Link
export const GET_TEMPLE_LIVE_LINK = 'GET_TEMPLE_LIVE_LINK';
export const SET_TEMPLE_LIVE_LINK = 'SET_TEMPLE_LIVE_LINK';
export const CREATE_TEMPLE_LIVE_LINK = 'CREATE_TEMPLE_LIVE_LINK';
export const UPDATE_TEMPLE_LIVE_LINK = 'UPDATE_TEMPLE_LIVE_LINK';
export const DELETE_TEMPLE_LIVE_LINK = 'DELETE_TEMPLE_LIVE_LINK';

//TODO---------------------Working-----------------------TODO// 

//! Banner
export const UPLOAD_APP_BANNER = "UPLOAD_APP_BANNER";
export const UPLOAD_WEB_BANNER = "UPLOAD_WEB_BANNER";
export const GET_APP_BANNERS = "GET_APP_BANNERS";
export const SET_APP_BANNERS = "SET_APP_BANNERS";
export const DELETE_BANNERS = "DELETE_BANNERS";
export const EDIT_BANNERS = "EDIT_BANNERS";
export const CHANGE_BANNER_STATUS = "CHANGE_BANNER_STATUS";

//! Teerth_Dham
export const UPLOAD_APP_TEERTH_DHAM = "UPLOAD_APP_TEERTH_DHAM";
export const UPLOAD_WEB_TEERTH_DHAM = "UPLOAD_WEB_TEERTH_DHAM";
export const GET_APP_TEERTH_DHAM = "GET_APP_TEERTH_DHAM";
export const SET_APP_TEERTH_DHAM = "SET_APP_TEERTH_DHAM";
export const DELETE_TEERTH_DHAM = "DELETE_TEERTH_DHAM";
export const EDIT_TEERTH_DHAM = "EDIT_TEERTH_DHAM";
export const CHANGE_TEERTH_DHAM_STATUS = "CHANGE_TEERTH_DHAM_STATUS";

//! Ecommerce
export const GET_ECOMMERCE_CATEGORY = 'GET_ECOMMERCE_CATEGORY';
export const SET_ECOMMERCE_CATEGORY = 'SET_ECOMMERCE_CATEGORY';
export const CREATE_ECOMMERCE_CATEGORY = 'CREATE_ECOMMERCE_CATEGORY';
export const UPDATE_ECOMMERCE_CATEGORY = 'UPDATE_ECOMMERCE_CATEGORY';
export const DELETE_ECOMMERCE_CATEGORY = 'DELETE_ECOMMERCE_CATEGORY';

export const GET_ECOMMERCE_PRODUCT = 'GET_ECOMMERCE_PRODUCT';
export const SET_ECOMMERCE_PRODUCT = 'SET_ECOMMERCE_PRODUCT';
export const CREATE_ECOMMERCE_PRODUCT = 'CREATE_ECOMMERCE_PRODUCT';
export const UPDATE_ECOMMERCE_PRODUCT = 'UPDATE_ECOMMERCE_PRODUCT';
export const DELETE_ECOMMERCE_PRODUCT = 'DELETE_ECOMMERCE_PRODUCT';

export const GET_ORDER_HISTORY = 'GET_ORDER_HISTORY';
export const SET_ORDER_HISTORY = 'SET_ORDER_HISTORY';
export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS';


//! Astro-Blog
//? Category
export const GET_ASTRO_BLOG_CATEGORY = 'GET_ASTRO_BLOG_CATEGORY';
export const SET_ASTRO_BLOG_CATEGORY = 'SET_ASTRO_BLOG_CATEGORY';
export const CREATE_ASTRO_BLOG_CATEGORY = 'CREATE_ASTRO_BLOG_CATEGORY';
export const UPDATE_ASTRO_BLOG_CATEGORY = 'UPDATE_ASTRO_BLOG_CATEGORY';
export const DELETE_ASTRO_BLOG_CATEGORY = 'DELETE_ASTRO_BLOG_CATEGORY';

export const ADD_ASTRO_BLOG = 'ADD_ASTRO_BLOG';
export const GET_ASTRO_BLOG = 'GET_ASTRO_BLOG';
export const SET_ASTRO_BLOG = 'SET_ASTRO_BLOG';
export const DELETE_ASTRO_BLOG = 'DELETE_ASTRO_BLOG';
export const UPDATE_ASTRO_BLOG = 'UPDATE_ASTRO_BLOG';

export const ADD_ASTROLOGERS_REVIEWS = "ADD_ASTROLOGERS_REVIEWS";
export const GET_ASTROLOGERS_REVIEWS = "GET_ASTROLOGERS_REVIEWS";
export const SET_ASTROLOGERS_REVIEWS = "SET_ASTROLOGERS_REVIEWS";
export const GET_APP_REVIEWS = "GET_APP_REVIEWS";
export const SET_APP_REVIEWS = "SET_APP_REVIEWS";
export const UPDATE_ASTROLOER_REVIEW_STATUS = "UPDATE_ASTROLOER_REVIEW_STATUS";
export const DELETE_ASTROLOGER_REVIEW = "DELETE_ASTROLOGER_REVIEW";
export const UPDATE_ASTROLOGER_REVIEW = "UPDATE_ASTROLOGER_REVIEW";

//Customer
// export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const GET_ALL_CUSTOMER = "GET_ALL_CUSTOMER";
export const SET_ALL_CUSTOMER = "SET_ALL_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const BAN_CUSTOMER = "BAN_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";

//Astrologer
export const GET_ALL_ASTROLOGER = "GET_ALL_ASTROLOGER";
export const SET_ALL_ASTROLOGER = "SET_ALL_ASTROLOGER";
export const UPDATE_ASTROLOGER_CHAT_STATUS = "UPDATE_ASTROLOGER_CHAT_STATUS";
export const UPDATE_ASTROLOER_CALL_STATUS = "UPDATE_ASTROLOER_CALL_STATUS";
export const GET_ENQUIRY_ASTROLOGERS = "GET_ENQUIRY_ASTROLOGERS";
export const SET_ENQUIRY_ASTROLOGERS = "SET_ENQUIRY_ASTROLOGERS";
export const UPDATE_ENQUIRY_STATUS = "UPDATE_ENQUIRY_STATUS";
export const UPDATE_ASTROLOGER_DATA = "UPDATE_ASTROLOGER_DATA";
export const ADD_ASTROLOGER = "ADD_ASTROLOGER";
export const VERIFY_UNVERIFY_ASTROLOGER = "VERIFY_UNVERIFY_ASTROLOGER";
export const DELETE_ASTROLOGER = "DELETE_ASTROLOGER";
export const GET_RECENT_LIVE_STREAMING = "GET_RECENT_LIVE_STREAMING";
export const SET_RECENT_LIVE_STREAMING = "SET_RECENT_LIVE_STREAMING";


export const CREATE_QUALIFICATION = "CREATE_QUALIFICATION";
export const GET_QUALIFICATION = "GET_QUALIFICATION";
export const SET_QUALIFICATION = "SET_QUALIFICATION";
export const UPDATE_QUALIFICATION = "UPDATE_QUALIFICATION";

export const GET_REQUEST_ASTROLOGER = "GET_REQUEST_ASTROLOGER";
export const SET_REQUEST_ASTROLOGER = "SET_REQUEST_ASTROLOGER";
export const UPDATE_REQUEST_ASTROLOGER = "UPDATE_REQUEST_ASTROLOGER";




// Gifts
export const CREATE_GIFT = "CREATE_GIFT";
export const GET_ALL_GIFT = "GET_ALL_GIFT";
export const SET_ALL_GIFT = "SET_ALL_GIFT";
export const UPDATE_GIFT = "UPDATE_GIFT";
export const DELETE_GIFT = "DELETE_GIFT";



//Notification
export const GET_CUSTOMER_NOTIFICATIONS = "GET_CUSTOMER_NOTIFICATIONS";
export const GET_ASTROLOGER_NOTIFICATIONS = "GET_ASTROLOGER_NOTIFICATIONS";
export const SET_CUSTOMER_NOTIFICATIONS = "GET_CUSTOMER_NOTIFICATIONS";
export const SET_ASTROLOGER_NOTIFICATIONS = "GET_ASTROLOGER_NOTIFICATIONS";
export const SEND_CUSTOMER_NOTIFICATIONS = "SEND_CUSTOMER_NOTIFICATIONS";
export const SEND_ASTROLOGER_NOTIFICATIONS = "SEND_ASTROLOGER_NOTIFICATIONS";
export const DELETE_CUSTOMER_NOTIFICATIONS = "GET_CUSTOMER_NOTIFICATIONS";
export const DELETE_ASTROLOGER_NOTIFICATIONS = "GET_ASTROLOGER_NOTIFICATIONS";
export const GET_AARTI_NOTIFICATIONS = 'GET_AARTI_NOTIFICATIONS';
export const SET_AARTI_NOTIFICATIONS = 'SET_AARTI_NOTIFICATIONS';
export const ON_AARTI_NOTIFICATIONS = 'ON_AARTI_NOTIFICATIONS';
export const DELETE_AARTI_NOTIFICATIONS = 'DELETE_AARTI_NOTIFICATIONS'


//Dashboard
export const GET_DASHBOARD = "GET_DASHBOARD";
export const SET_DASHBOARD = "SET_DASHBOARD";

export const GET_DASHBOARD_DATA = "GET_DASHBOARD_DATA";
export const SET_DASHBOARD_DATA = "SET_DASHBOARD_DATA";
export const GET_EARNING_CHART = 'GET_EARNING_CHART';
export const SET_EARNING_CHART = 'SET_EARNING_CHART';
export const GET_EARNING_GRAPH = 'GET_EARNING_GRAPH';
export const SET_EARNING_GRAPH = 'SET_EARNING_GRAPH';

//Reports
export const GET_ADMIN_EARNINGS = "GET_ADMIN_EARNINGS";
export const SET_ADMIN_EARNINGS = "SET_ADMIN_EARNINGS";
export const GET_RECIEPT_SUMMARY = 'GET_RECIEPT_SUMMARY'
export const SET_RECIEPT_SUMMARY = 'SET_RECIEPT_SUMMARY'

//Language
export const CREATE_LANGUAGE = "CREATE_LANGUAGE";
export const GET_ALL_LANGUAGE = "GET_ALL_LANGUAGE";
export const SET_ALL_LANGUAGE = "SET_ALL_LANGUAGE";
export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";
export const DELETE_LANGUAGE = "DELETE_LANGUAGE";

//Country
export const GET_ALL_COUNTRY = "GET_ALL_COUNTRY";
export const SET_ALL_COUNTRY = "SET_ALL_COUNTRY";

//Recharge Plan

export const CREATE_RECHARGE_PLAN = 'CREATE_RECHARGE_PLAN';
export const GET_RECHARGE_PLAN = 'GET_RECHARGE_PLAN'
export const SET_RECHARGE_PLAN = 'SET_RECHARGE_PLAN'
export const UPDATE_RECHARGE_PLAN = 'UPDATE_RECHARGE_PLAN'
export const DELETE_RECHARGE_PLAN = 'DELETE_RECHARGE_PLAN'
export const UPDATE_RECHARGE_PLAN_STATUS = 'UPDATE_RECHARGE_PLAN_STATUS'

//FirstRecharge Offer
export const CREATE_FIRST_RECHARGE_OFFER = 'CREATE_FIRST_RECHARGE_OFFER'
export const GET_FIRST_RECHARGE_OFFER = 'GET_FIRST_RECHARGE_OFFER'
export const SET_FIRST_RECHARGE_OFFER = 'SET_FIRST_RECHARGE_OFFER'
export const UPDATE_FIRST_RECHARGE_OFFER = 'UPDATE_FIRST_RECHARGE_OFFER'
export const UPDATE_FIRST_RECHARGE_OFFER_STATUS = 'UPDATE_FIRST_RECHARGE_OFFER_STATUS'
export const DELETE_FIRST_RECHARGE_OFFER = 'DELETE_FIRST_RECHARGE_OFFER'

// Pages
export const ADD_ASK_QUESTIONS = "ADD_ASK_QUESTIONS"
export const GET_ASK_QUESTION = "GET_ASK_QUESTION"
export const SET_ASK_QUESTION = "SET_ASK_QUESTION"
export const DELETE_ASK_QUESTION = "DELETE_ASK_QUESTION"
export const UPDATE_ASK_QUESTION = "UPDATE_ASK_QUESTION"

export const ADD_RELIGION_SPRITUALITY = "ADD_RELIGION_SPRITUALITY"
export const GET_ALL_RELIGION_SPRITUALITY = "GET_ALL_RELIGION_SPRITUALITY"
export const SET_ALL_RELIGION_SPRITUALITY = "SET_ALL_RELIGION_SPRITUALITY"
export const DELETE_RELIGION_SPRITUALITY = "DELETE_RELIGION_SPRITUALITY"
export const UPDATE_RELIGION_SPRITUALITY = "UPDATE-RELIGION-SPRITUALITY"

export const ADD_ASTRO_MAGAZINE = "ADD_ASTRO_MAGAZINE"
export const GET_ALL_ASTRO_MAGAZINE = "GET_ALL_ASTRO_MAGAZINE"
export const SET_ALL_ASTRO_MAGAZINE = "SET_ALL_ASTRO_MAGAZINE"
export const DELETE_ASTRO_MAGAZINE = "DELETE_ASTRO_MAGAZINE"
export const UPDATE_ASTRO_MAGAZINE = "UPDATE_ASTRO_MAGAZINE"

export const ADD_ANNOUNCEMENT = "ADD_ANNOUNCEMENT"
export const GET_ALL_ANNOUNCEMENT = "GET_ALL_ANNOUNCEMENT"
export const SET_ALL_ANNOUNCEMENT = "SET_ALL_ANNOUNCEMENT"
export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT"
export const UPDATE_ANNOUNCEMENT = "UPDATE_ANNOUNCEMENT"

export const ADD_BIRHAT_HOROSCOPE = "ADD_BIRHAT_HOROSCOPE"
export const GET_ALL_BIRHAT_HOROSCOPE = "GET_ALL_BIRHAT_HOROSCOPE"
export const SET_ALL_BIRHAT_HOROSCOPE = "SET_ALL_BIRHAT_HOROSCOPE"
export const DELETE_BIRHAT_HOROSCOPE = "DELETE_BIRHAT_HOROSCOPE"
export const UPDATE_BIRHAT_HOROSCOPE = "UPDATE_BIRHAT_HOROSCOPE"

export const ADD_AUSPICIOUS_TIME = "ADD_AUSPICIOUS_TIME"
export const GET_ALL_AUSPICIOUS_TIME = "GET_ALL_AUSPICIOUS_TIME"
export const SET_ALL_AUSPICIOUS_TIME = "SET_ALL_AUSPICIOUS_TIME"
export const DELETE_ALL_AUSPICIOUS_TIME = "DELETE_ALL_AUSPICIOUS_TIME"
export const UPDATE_AUSPICIOUS_TIME = "UPDATE_AUSPICIOUS_TIME"

export const ADD_DAILY_PANCHANG = "ADD_DAILY_PANCHANG"
export const GET_ALL_DAILY_PANCHANG = "GET_ALL_DAILY_PANCHANG"
export const SET_ALL_DAILY_PANCHANG = "SET_ALL_DAILY_PANCHANG"
export const DELETE_DAILY_PANCHANG = "DELETE_DAILY_PANCHANG"
export const UPDATE_DAILY_PANCHANG = "UPDATE_DAILY_PANCHANG"

export const ADD_YELLOW_BOOK = "ADD_YELLOW_BOOK"
export const GET_ALL_YELLOW_BOOK = "GET_ALL_YELLOW_BOOK"
export const SET_ALL_YELLOW_BOOK = "SET_ALL_YELLOW_BOOK"
export const DELETE_YELLOW_BOOK = "DELETE_YELLOW_BOOK"
export const UPDATE_YELLOW_BOOK = "UPDATE_YELLOW_BOOK"



export const CREATE_APP_TUTORIALS = "CREATE_APP_TUTORIALS"
export const GET_APP_TUTORIALS = "GET_APP_TUTORIALS"
export const SET_APP_TUTORIALS = "SET_APP_TUTORIALS"
export const DELETE_APP_TUTORIALS = "DELETE_APP_TUTORIALS"



// App Astrokunj

export const ADD_NUMEROLOGY = "ADD_NUMEROLOGY"
export const SET_NUMEROLOGY = "SET_NUMEROLOGY"
export const GET_NUMEROLOGY = "GET_NUMEROLOGY"
export const DELETE_NUMEROLOGY = "DELETE_NUMEROLOGY"
export const UPDATE_NUMEROLOGY = "UPDATE_NUMEROLOGY"

export const ADD_VIVAHMUHURAT = "ADD_VIVAHMUHURAT"
export const SET_VIVAHMUHURAT = "SET_VIVAHMUHURAT"
export const GET_VIVAHMUHURAT = "GET_VIVAHMUHURAT"
export const DELETE_VIVAHMUHURAT = "DELETE_VIVAHMUHURAT"
export const UPDATE_VIVAHMUHURAT = "UPDATE_VIVAHMUHURAT"


export const ADD_MUNDANMUHURAT = "ADD_MUNDANMUHURAT"
export const SET_MUNDANMUHURAT = "SET_MUNDANMUHURAT"
export const GET_MUNDANMUHURAT = "GET_MUNDANMUHURAT"
export const DELETE_MUNDANMUHURAT = "DELETE_MUNDANMUHURAT"
export const UPDATE_MUNDANMUHURAT = "UPDATE_MUNDANMUHURAT"

export const ADD_ANNAPRASHAN = "ADD_ANNAPRASHAN"
export const SET_ANNAPRASHAN = "SET_ANNAPRASHAN"
export const GET_ANNAPRASHAN = "GET_ANNAPRASHAN"
export const DELETE_ANNAPRASHAN = "DELETE_ANNAPRASHAN"
export const UPDATE_ANNAPRASHAN = "UPDATE_ANNAPRASHAN"


// Services History

export const GET_RECHARGE_SERVICES_HISTORY = 'GET_RECHARGE_SERVICES_HISTORY'
export const SET_RECHARGE_SERVICES_HISTORY = 'SET_RECHARGE_SERVICES_HISTORY'

//! Panchang
export const GET_PANCHANG = 'GET_PANCHANG';
export const SET_PANCHANG = 'SET_PANCHANG';
export const ON_PANCHANG = 'ON_PANCHANG';

export const GET_PANCHANG_VIVAH = 'GET_PANCHANG_VIVAH';
export const SET_PANCHANG_VIVAH = 'SET_PANCHANG_VIVAH';
export const ON_PANCHANG_VIVAH = 'ON_PANCHANG_VIVAH';

export const GET_PANCHANG_MUHURAT_VAAHAN = 'GET_PANCHANG_MUHURAT_VAAHAN';
export const SET_PANCHANG_MUHURAT_VAAHAN = 'SET_PANCHANG_MUHURAT_VAAHAN';
export const ON_PANCHANG_MUHURAT_VAAHAN = 'ON_PANCHANG_MUHURAT_VAAHAN';

export const GET_PANCHANG_MUHURAT_SAMPATTI = 'GET_PANCHANG_MUHURAT_SAMPATTI';
export const SET_PANCHANG_MUHURAT_SAMPATTI = 'SET_PANCHANG_MUHURAT_SAMPATTI';
export const ON_PANCHANG_MUHURAT_SAMPATTI = 'ON_PANCHANG_MUHURAT_SAMPATTI';

export const GET_PANCHANG_GRAHPRAVESH = 'GET_PANCHANG_GRAHPRAVESH';
export const SET_PANCHANG_GRAHPRAVESH = 'SET_PANCHANG_GRAHPRAVESH';
export const ON_PANCHANG_GRAHPRAVESH = 'ON_PANCHANG_GRAHPRAVESH';

//# Letter to God
export const ON_UPDATE_PROMPT = 'ON_UPDATE_PROMPT';
export const GET_UPDATE_PROMPT = 'GET_UPDATE_PROMPT';
export const SET_UPDATE_PROMPT = 'SET_UPDATE_PROMPT';